import React, { useEffect, useState } from 'react';
import { Alert, Card, Col, Row, Spinner } from 'react-bootstrap';
import { getMentorTeams, getTeam } from '../../api/hackathonApi';
import { getInitials, getStoredUser } from '../../utils/authUser';
import styles from './TeamDetails.module.css';

const TeamDetails = () => {
  const [teams, setTeams] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const getStatusColorClass = (progress) => progress >= 80 ? { text: styles.statusGreen, bg: styles.bgGreen } : progress >= 60 ? { text: styles.statusOrange, bg: styles.bgOrange } : { text: styles.statusRed, bg: styles.bgRed };

  useEffect(() => { (async () => { setLoading(true); setError(''); try { const user = getStoredUser(); const rows = await getMentorTeams(user?.id); const unique = Array.from(new Map((rows || []).filter((r) => r.teamId).map((r) => [r.teamId, r])).values()); const full = await Promise.all(unique.map(async (r) => ({ ...r, detail: await getTeam(r.teamId).catch(() => null) }))); setTeams(full); } catch (e) { setError(e.message || 'Cannot load mentor teams'); } finally { setLoading(false); } })(); }, []);

  return (
    <div className="py-2"><div className={styles.pageHeader}><h1 className={styles.pageTitle}>Team Details</h1><div className={styles.pageSubtitle}>Detailed overview of your assigned teams</div></div>{error && <Alert variant="danger">{error}</Alert>}{loading ? <div className="text-center py-4"><Spinner size="sm" className="me-2" />Loading...</div> : teams.length === 0 ? <Alert variant="info">No assigned teams.</Alert> : teams.map((team) => { const d = team.detail || {}; const members = d.members || []; const progress = members.length ? Math.min(100, (members.length / 5) * 100) : 20; const statusColors = getStatusColorClass(progress); return <div key={team.teamId} className={styles.teamSection}><div className={styles.sectionHeader}>{team.teamName} <span className={styles.sectionCategory}>· {team.trackName}</span></div><Row><Col md={7} className="mb-4 mb-md-0"><Card className={styles.detailCard}><Card.Body className="p-4"><h3 className={styles.cardTitle}>Project Details</h3><div className={styles.projectTitleLabel}>Title</div><div className={styles.projectTitle}>{d.projectName || d.name || team.teamName}</div><div className={styles.projectSubtitle}>{team.roundName ? `Current round: ${team.roundName}` : 'No round context'}</div><div className={styles.projectDescriptionLabel}>Description</div><div className={styles.projectDescription}>{d.description || 'No project description field in backend yet.'}</div><div className={styles.tagList}><span className={styles.techTag}>{team.trackName}</span><span className={styles.techTag}>{d.status || team.teamStatus || 'active'}</span></div><div className={styles.progressContainer}><div className={styles.progressHeader}><span className={styles.progressLabel}>Roster Progress</span><span className={`${styles.progressStatus} ${statusColors.text}`}>{Math.round(progress)}% - {(d.status || team.teamStatus || 'active')}</span></div><div className={styles.progressBarContainer}><div className={`${styles.progressBarFill} ${statusColors.bg}`} style={{ width: `${progress}%` }}></div></div></div></Card.Body></Card></Col><Col md={5}><Card className={styles.detailCard}><Card.Body className="p-4"><h3 className={styles.cardTitle}>Team Roster</h3><div className={styles.rosterList}>{members.length === 0 ? <div className="text-muted">No members loaded.</div> : members.map((member) => <div key={member.userId || member.id} className={styles.rosterItem}><div className={styles.memberAvatar}>{getInitials(member.fullName || member.email || member.userId)}</div><div className={styles.memberInfo}><span className={styles.memberName}>{member.fullName || member.email || member.userId}</span><span className={styles.memberRole}>{member.role || 'member'}</span></div></div>)}</div></Card.Body></Card></Col></Row></div>; })}</div>
  );
};

export default TeamDetails;
